# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/infer
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

hello world
--boundary--

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
